pip install pafy
pip install youtube_dl
pip install pandas
pip install pillow
pip install ipython
pip install configobj
pip install opencv-python==4.2.0
pip install tensorflow==1.13.1
pip install keras==2.3.1
pip install scikit-image
pip install scipy
pip install numpy
pip install matplotlib
pip install scikit-image
pip install deepdish==0.3
pip install absl-py
pip install ipdb
pip install opendr==0.77
